resources:
- name: src-code
  type: git
  source:
    uri: https://github.com/nikslos/jumpstarter-spring-app.git
    branch: develop
    username: (( $USERNAME ))
    password: (( $PASSWORD ))
jobs:
- name: build-pipeline
  serial: true
  plan:
  - get: src-code
    trigger: true
  - task: build-jar
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs: 
        - name: src-code
      run: 
        path: sh
        dir: jumpstarter-spring-app
        args:
          - -exc
          - |
             mvn clean install ./target/gs-spring-boot-0.1.0.jar

