resources:
- name: src-code
  type: git
  source:
    uri: https://github.com/nikslos/jumpstarter-spring-app.git
    branch: develop
    username: (( $USERNAME ))
    password: (( $PASSWORD ))
jobs:
- name: build-pipeline
  serial: true
  plan:
  - get: src-code
    trigger: true
  - task: build-jar
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
      inputs: 
        - name: src-code
      outputs:
        - name: build-jar
      caches: 
        - path: src-code/ .m2
      run:
        path: sh
        args:
          - -exc
          - |
             echo "hello"
             mvn -f src-code/pom.xml package -Dmaven.repo.local=src-code/.m2
